services:
  ros2:
    # Using custom, slightly modified ROS2 image
    image: ros-custom:latest
    build:
      context: ./build
      dockerfile: Dockerfile
    user: ${USER_UID:?}:${USER_GID:?}
    ipc: host
    volumes:
      # Just a shared misc data directory for whatever you want. Not necessary.
      - ./data:/data

      # For sharing X session, allowing graphical applications to run
      - /tmp/.X11-unix/:/tmp/.X11-unix/

      # Volumes for container persistence
      - home:/home
      - root:/root
      - etc:/etc
      - log:/log
      - usr:/usr
      - var:/var
    environment:
      # For X session
      - DISPLAY
      - XAUTHORITY
    # For GPU acceleration
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video

# This is written weird and verbosely for two reasons:
# 1. You can't bind mount the container's root FS out to a host directory (ex: `./container:/` throws an error if used as a volume).
#    So we mount each important directory under / instead.
# 2. If you use normal bind mount syntax it will make the directory inside the container empty (overriding the initial contents from the image).
#    So we use named volume syntax to make it populate the directories with the initial content (we wouldn't want /usr to start empty or something)
volumes:
  home:
    driver: local
    driver_opts:
      device: ${CONTAINER_ROOT_DATA_DIR:?}/home
      type: none
      o: bind
  root:
    driver: local
    driver_opts:
      device: ${CONTAINER_ROOT_DATA_DIR:?}/root
      type: none
      o: bind
  etc:
    driver: local
    driver_opts:
      device: ${CONTAINER_ROOT_DATA_DIR:?}/etc
      type: none
      o: bind
  log:
    driver: local
    driver_opts:
      device: ${CONTAINER_ROOT_DATA_DIR:?}/log
      type: none
      o: bind
  usr:
    driver: local
    driver_opts:
      device: ${CONTAINER_ROOT_DATA_DIR:?}/usr
      type: none
      o: bind
  var:
    driver: local
    driver_opts:
      device: ${CONTAINER_ROOT_DATA_DIR:?}/var
      type: none
      o: bind
